# Generates jevaudit对账系统能力证明.md from reconcile/ and fixtures/ (run 2, listener v0.3.0-freeze)
import json, hashlib
R=lambda f: json.load(open('reconcile/'+f+'.json')); X=lambda f: json.load(open('fixtures/'+f+'.json'))
sha=lambda p: hashlib.sha256(open(p,'rb').read()).hexdigest()
S=R('summary'); n=sum(S.values()); N=len(S)
L=[]; a=L.append
a("# jevaudit 对账系统能力证明（v0.3.0-freeze）\n")
a("日期：2026-10-05 · 对象：openship-fork 24h 账本副本（raw/ledger/ 字节复制到 test-fixtures/ledger_original/，生产账本未改）\n")
a(f"**结论：{n}/{N} 通过**（" + "、".join(k for k in S) + "）。\n")
a(f"- listener.py sha256 `{sha('../listener/listener.py')}`（tag `listener-v0.3.0-freeze`）")
a(f"- test_listener.py sha256 `{sha('../listener/test_listener.py')}`，13 个单元测试全部 OK")
a("- 第一次跑（修复前，listener v3 `0bd06180`）：T4c 失败，其余通过。之前消息里写的「T4c PASS」不对，当时实际是 FAIL。修复后本次全部重跑，T4c 通过。修复后输出在第 3 节，修复前输出在第 4 节。\n")
a("## 1. 方法\n")
a("- 每项测试单独 fixture_id：备份 → 注入 → 对账 → 恢复 → SHA256 对比（restore_and_verify.sh 自动执行）。恢复后 SHA256 不一致 → 整轮作废。")
a("- 对账 = 从 Polygon RPC 重拉 OrderFilled 日志，按 2182 个跟踪钱包过滤，与账本逐笔比对（tx + log_index）；每窗口 10 个区块用 3 个节点交叉核对。")
a("- 判定：只出现 1 条、且与预期一致的 finding 才算通过；多报或少报都算失败。")
a("- T1 的伪造记录重新计算了 output_hash，所以账本自身的指纹检查发现不了，只能靠链上比对发现。")
a("- 中间窗口 W = 94860000–94860039（事先确认无已知缺口）；尾部窗口 94883008–94883047（最后区块 94883047 取自 checkpoint next_block−1）。")
a("- gzip 文件被改后重新压缩，字节必然不同，所以被改文件比对解压后内容的 SHA256；未改文件比对文件字节 SHA256。每项测试都核对生产账本未变。")
a("- 61/61 只在前面全部通过后才执行（restore_and_verify.sh 里写死）。")
a("- 范围说明：T1–T3.6、T5、61/61 测的是对账（jevaudit/audit），T4/T4c 测的是 listener.py。listener 修复不影响对账代码，但按指令全部重跑。\n")
a("## 2. 逐项记录\n")
a("| fixture_id | 注入 | 预期 | 实际 | 原始 sha256（内容） | 注入后 sha256（内容） | 恢复后一致 | 结果 |")
a("|---|---|---|---|---|---|---|---|")
for f in ['T1','T2','T3','T3.5','T3.6','T5']:
    d=R(f); x=X(f)
    rest=all(v['equal'] for v in x['restore'].values()) and all(x['production_untouched'].values())
    act="; ".join(c['code']+(" "+str(c.get('block')) if c.get('block') else "")+(f" ({c['missing_fills']}笔)" if c.get('missing_fills') else "") for c in d['actual'])
    a(f"| {f} | {x['inject']} | {x['expected']} | {act} | `{x['original_content_sha256'][:16]}` | `{(x.get('modified_content_sha256') or '文件已删')[:16]}` | {'是' if rest else '否'} | {'通过' if d['pass'] else '失败'} |")
t4=R('T4')
a(f"| T4 | mock RPC：head=256，255 有数据，256 空 | UNAVAILABLE / 不推进游标 / pending_tip=256；第二轮写入 256 | T4a、T4b 全部断言 OK（第 3 节） | — | — | — | {'通过' if t4.get('T4a') and t4.get('T4b') else '失败'} |")
a(f"| T4c | mock RPC：CONFIRM_DEPTH=0，节点在 tip 同时滞后，两个节点都对 256 返回空 | 256 = UNAVAILABLE，游标停在 255，第二轮写入 256 | 全部断言 OK（第 3、4 节） | — | — | — | {'通过' if t4.get('T4c') else '失败'} |")
rows=json.load(open('reconcile/case61.json'))
a(f"| 61/61 | 不注入，真实 24h 事故 | 5 区块 61 笔 | {sum(r['match'] for r in rows)}/5 区块，{sum(r['missing_found'] for r in rows)}/61 笔 | — | — | — | {'通过' if S['61/61'] else '失败'} |")
a("\n原始文件 sha256（chain_listener_20261003.jsonl.gz 字节）：`16fce6de4b5ec6217aa94da677c00b01462eed506eda63bfb1773401603b7be5`；解压内容：`28e5a7f504255aeb1f354673e3bcfcc1a315c17eb900a4480d64def7bb1863f0`。20261002 分片：`5d57a98d53052c4f9490f6478ebaa2b3917282207dfae21fdca0fe01bf3a7e22`。\n")
a("### 每项恢复验证明细\n")
for f in ['T1','T2','T3','T3.5','T3.6','T5']:
    x=X(f)
    for fn,v in x['restore'].items():
        a(f"- {f} · {fn} · {v['kind']} · 恢复 `{v['restored_sha256'][:16]}` = 原始 `{v['original_sha256'][:16]}` → {'一致' if v['equal'] else '不一致'}")
    a(f"- {f} · 生产账本未变：{'是' if all(x['production_untouched'].values()) else '否'}")
t5=R('T5')
a("\n### T5 假阳性明细\n")
for k in ('middle','tail'):
    c=t5[k]['counts']
    a(f"- {k} {t5[k]['range']}：账本 {c['ledger_fills']} 笔，链上跟踪钱包 {c['chain_fills_tracked']} 笔，对上 {c['matched']}，缺 {c['missing_in_ledger']}，多 {c['extra_in_ledger']}；指纹失败 {t5[k]['integrity']['n_failed']}；三节点抽查 {t5[k]['node_agreement_sample']['all_nodes_identical']}/{t5[k]['node_agreement_sample']['blocks']} 一致")
a(f"- 分片：应有 {t5['partitions']['expected']}，实有 {t5['partitions']['present']}，缺 {t5['partitions']['missing']}")
a("- T5 只在两个 40 区块窗口上跑（省积分），不是全 24h 重拉。全量 3,900,170 笔重拉是之前做的那次。\n")
a("## 3. T4 / T4c mock RPC 输出全文（本次，修复后）\n")
a("```\n"+open('reconcile/T4_mock_rpc_output.txt').read().strip()+"\n```\n")
a("- T4a = 生产配置（CONFIRM_DEPTH=10）：只处理到 head−10=246，256 不碰，pending_tip=256；head 到 266 后 256 正常写入一次。")
a("- T4b = 指令原样场景（深度关掉，只有节点 a 能答）：256 = UNAVAILABLE，last_processed=255，pending_tip=256；第二轮 256 写入、游标到 256。")
a("- T4c = 深度关掉，两个节点对 256 都返回空：256 离 head 不到 MIN_SAFE_DEPTH，判 UNAVAILABLE，游标停在 255；第二轮 256 写入一次。\n")
a("## 4. T4c 修复前输出全文（第一次跑，listener v3 `0bd06180`）\n")
t=open('reconcile/run1_before_fix/T4_mock_rpc_output.txt').read()
a("```\n"+t[t.index('=== T4c'):].strip()+"\n```\n")
a("- 修复前：两个节点都返回空 → 256 被判 CONFIRMED_EMPTY，游标越过 256，第二轮因 last_processed=256 直接跳过，256 的数据丢失。和 24h 事故是同一种丢失。")
a("- 修复：只改 listener.py，Gate 未动。见第 5 节。\n")
a("## 5. 关于配置参数与安全不变量的边界\n")
a("- 性能参数可调，安全不变量不可调。")
a("- `CONFIRM_DEPTH`（环境变量，默认 10）是性能参数：决定每轮读到 head 往回多少个区块。可以设成 0，启动不会被拒绝。")
a("- `MIN_SAFE_DEPTH = 5` 硬编码在 listener.py，不读任何环境变量（单元测试 `test_floor_is_not_configurable` 验证）。")
a("- 生效深度 = max(CONFIRM_DEPTH, MIN_SAFE_DEPTH)。")
a("- `CONFIRMED_EMPTY` 的条件：至少 2 个不同节点都返回空 **并且** 区块号 < head − 生效深度（严格小于）。不满足就是 `UNAVAILABLE`：游标停在它前面，下一轮重试。")
a("- 所以把 CONFIRM_DEPTH 设成 0 只会让读得更靠近 tip，不会让“节点说空”在 tip 上被当成确认为空。")
a("- 边界值（单元测试验证）：生效深度 5、block 256 时，head=260 → UNAVAILABLE；head=261 → 可判 CONFIRMED_EMPTY。")
a("- 副作用：默认深度 10 时，最新读到的 head−10 区块如果为空，会多等一轮（约 2 秒）才确认为空。不影响数据。\n")
a("## 6. 61 笔真实案例复现\n")
a("| 区块 | 对账找到缺失 | 已知缺失 | 前一区块重复记录 | 一致 |")
a("|---|---|---|---|---|")
for r in rows: a(f"| {r['block']} | {r['missing_found']} | {r['missing_expected']} | {r['dups_in_prev_block']} | {'是' if r['match'] else '否'} |")
a(f"| 合计 | {sum(r['missing_found'] for r in rows)} | {sum(r['missing_expected'] for r in rows)} | {sum(r['dups_in_prev_block'] for r in rows)} | {sum(r['match'] for r in rows)}/5 |")
a("\n## 7. 文件\n")
a("- test-fixtures/：injector.py、t4_tip_race.py、restore_and_verify.sh、mkreport.py、ledger_original.sha256.json；fixtures/<fid>.json（注入明细 + sha）；reconcile/<fid>.json（对账输出）、reconcile/T4_mock_rpc_output.txt、reconcile/case61.json、reconcile/summary.json、reconcile/listener_unittest.txt、run.log。")
a("- 第一次跑的证据原样保留：test-fixtures/reconcile/run1_before_fix/、test-fixtures/fixtures_run1/。")
a("- test-fixtures/ledger_original/ 是 raw/ledger/ 的字节副本（sha 见 ledger_original.sha256.json），不重复推送。")
a("- jevaudit/audit/findings.py（check_partitions、classify）在 HCTDIP/jevaudit。")
a("- listener/CHANGELOG.md v0.3.0-freeze 条目；SHA256SUMS_listener-v0.3.0-freeze.txt。")
open('jevaudit对账系统能力证明.md','w').write("\n".join(L)+"\n")
print(n,N)
